// JobMatch AI — Runtime Configuration
// This file is auto-generated by Netlify build for production.
// For local dev, values fall back to localhost defaults.
const CONFIG = {
  API_BASE_URL: window.JOBMATCH_API_URL || 'http://localhost:8000',
  API_KEY: window.JOBMATCH_API_KEY || ''
};
