// Job titles from dataset
const JOB_TITLES = [
    "Account Director", "Account Executive", "Account Manager", "Accountant", "Administrative Assistant",
    "Aerospace Engineer", "Architect", "Architectural Designer", "Art Director", "Art Teacher",
    "Back-End Developer", "Brand Ambassador", "Brand Manager", "Business Analyst", "Business Development Manager",
    "Chemical Analyst", "Chemical Engineer", "Civil Engineer", "Content Writer", "Copywriter",
    "Customer Service Manager", "Customer Service Representative", "Customer Success Manager", "Customer Support Specialist",
    "Data Analyst", "Data Engineer", "Data Entry Clerk", "Data Scientist", "Database Administrator", "Database Developer",
    "Dental Hygienist", "Digital Marketing Specialist", "Electrical Designer", "Electrical Engineer",
    "Email Marketing Specialist", "Environmental Consultant", "Environmental Engineer",
    "Event Coordinator", "Event Manager", "Event Planner", "Executive Assistant",
    "Family Lawyer", "Family Nurse Practitioner", "Finance Manager", "Financial Advisor", "Financial Analyst",
    "Financial Controller", "Financial Planner", "Front-End Developer", "Front-End Engineer",
    "Graphic Designer", "HR Coordinator", "HR Generalist", "HR Manager", "Human Resources Manager",
    "IT Administrator", "IT Manager", "IT Support Specialist", "Interior Designer", "Inventory Analyst",
    "Investment Advisor", "Investment Analyst", "Investment Banker", "Java Developer", "Key Account Manager",
    "Landscape Architect", "Landscape Designer", "Legal Advisor", "Legal Assistant", "Legal Counsel", "Legal Secretary",
    "Litigation Attorney", "Market Analyst", "Market Research Analyst", "Marketing Analyst", "Marketing Coordinator",
    "Marketing Director", "Marketing Manager", "Marketing Specialist", "Mechanical Designer", "Mechanical Engineer",
    "Network Administrator", "Network Analyst", "Network Engineer", "Network Security Specialist", "Network Technician",
    "Nurse Manager", "Nurse Practitioner", "Occupational Therapist", "Office Manager", "Operations Manager",
    "Paralegal", "Pediatrician", "Personal Assistant", "Pharmaceutical Sales Representative", "Physical Therapist",
    "Physician Assistant", "Process Engineer", "Procurement Coordinator", "Procurement Manager", "Procurement Specialist",
    "Product Designer", "Product Manager", "Project Coordinator", "Project Manager", "Psychologist",
    "Public Relations Specialist", "Purchasing Agent", "QA Analyst", "QA Engineer", "Quality Assurance Analyst",
    "Registered Nurse", "Research Analyst", "Research Scientist", "SEM Specialist", "SEO Analyst", "SEO Specialist",
    "Sales Associate", "Sales Consultant", "Sales Manager", "Sales Representative",
    "Social Media Coordinator", "Social Media Manager", "Social Worker", "Software Architect",
    "Software Developer", "Software Engineer", "Software Tester", "Speech Therapist", "Structural Engineer",
    "Substance Abuse Counselor", "Supply Chain Analyst", "Supply Chain Manager",
    "Systems Administrator", "Systems Analyst", "Systems Engineer", "Tax Consultant", "Teacher", "Technical Writer",
    "UI Developer", "UX Researcher", "UX/UI Designer", "Urban Planner", "Veterinarian",
    "Web Designer", "Web Developer", "Wedding Planner"
];

// Curated common tech and professional skills
const COMMON_SKILLS = [
    "Python", "JavaScript", "Java", "C++", "C#", "Ruby", "PHP", "Swift", "Kotlin", "Go", "Rust", "TypeScript",
    "SQL", "HTML", "CSS", "React", "Angular", "Vue.js", "Node.js", "Django", "Flask", "Spring", "ASP.NET",
    "Express.js", "Laravel", "Ruby on Rails", "TensorFlow", "PyTorch", "Scikit-learn", "Pandas", "NumPy",
    "Tableau", "Power BI", "Excel", "R", "MATLAB", "SAS", "AWS", "Azure", "Google Cloud", "Docker", "Kubernetes",
    "Jenkins", "Git", "GitHub", "GitLab", "REST API", "GraphQL", "MongoDB", "PostgreSQL", "MySQL", "Oracle", "Redis",
    "Firebase", "Agile", "Scrum", "Kanban", "JIRA", "Confluence", "Salesforce", "HubSpot", "Google Analytics",
    "SEO", "SEM", "Content Marketing", "Email Marketing", "Social Media Marketing", "PPC",
    "Adobe Photoshop", "Adobe Illustrator", "Figma", "Sketch", "InVision", "AutoCAD", "SolidWorks",
    "Project Management", "Communication", "Leadership", "Problem Solving", "Critical Thinking", "Time Management",
    "Teamwork", "Adaptability", "Creativity", "Attention to Detail", "Data Analysis", "Machine Learning", "Deep Learning",
    "Natural Language Processing", "Computer Vision", "DevOps", "CI/CD", "Microservices", "Cloud Computing",
    "Cybersecurity", "Network Security", "Penetration Testing", "Blockchain", "IoT", "AR/VR", "UI/UX Design",
    "User Research", "Wireframing", "Prototyping", "Financial Analysis", "Accounting", "Budgeting", "Forecasting",
    "Risk Management", "Compliance", "Legal Research", "Contract Negotiation", "Supply Chain Management",
    "Inventory Management", "Quality Assurance", "Process Improvement", "Six Sigma", "Lean Manufacturing",
    "Customer Service", "Sales", "Business Development", "Market Research", "Strategic Planning", "Change Management",
    "Training", "Mentoring", "Data Visualization", "Statistical Analysis", "A/B Testing", "Copywriting",
    "Technical Writing", "Public Speaking", "Presentation Skills", "Negotiation", "Conflict Resolution",
    "Emotional Intelligence", "Cross-functional Collaboration", "Vendor Management", "Procurement",
    "ERP Systems", "CRM Software", "Microsoft Office", "Google Workspace", "Slack", "Zoom", "Trello", "Asana", "Monday.com",
    "ETL", "Data Warehousing", "Big Data", "Hadoop", "Spark", "Kafka", "Airflow", "Snowflake", "Redshift",
    "Terraform", "Ansible", "Linux", "Windows Server", "Active Directory", "VMware", "Networking", "TCP/IP",
    "DNS", "DHCP", "VPN", "Firewalls", "Load Balancing", "ITIL", "ISO 27001", "GDPR", "HIPAA", "SOC 2"
];
